/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import interfaz.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaise
 */
public class DarBaja extends javax.swing.JInternalFrame {

    /**
     * Creates new form darBaja
     */
    public DarBaja() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        cargarTabla();
    }

    private void cargarTabla() {
        try {
            Conexion cc = new Conexion();
            Connection cn = cc.conectar();
            String[] datos = new String[7];
            String[] encabezado = {"Codigo", "Nombre", "Marca", "Precio Unitario", "Cantidad", "Bodega", "Estado"};
            jTblArticulos.setModel(new DefaultTableModel(null, encabezado) {
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            });
            DefaultTableModel model = (DefaultTableModel) this.jTblArticulos.getModel();
            String sql = "";
            sql = "SELECT P.ID_PRO, P.NOM_PRO, P.MAR_PRO,P.PRE_UNI_PRO,P.EST_PRO,D.CAN_PRO_BOD, B.NOM_BOD FROM PRODUCTOS P, DETALLE_BODEGAS D, BODEGAS B WHERE P.ID_PRO = D.ID_PRO_BOD && D.ID_BOD_PER = B.ID_BOD";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString("P.ID_PRO");
                datos[1] = rs.getString("P.NOM_PRO");
                datos[2] = rs.getString("P.MAR_PRO");
                datos[3] = rs.getString("P.PRE_UNI_PRO");
                datos[4] = rs.getString("D.CAN_PRO_BOD");
                datos[5] = rs.getString("B.NOM_BOD");
                datos[6] = rs.getString("P.EST_PRO");
                model.addRow(datos);

            }
            this.jTblArticulos.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblArticulos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBtnCerrar = new javax.swing.JButton();
        jBtnActDes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jTblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblArticulos);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarActionPerformed(evt);
            }
        });

        jBtnActDes.setText("Activar/Desactivar");
        jBtnActDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActDesActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnActDes)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnCerrar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnCerrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnActDes, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarActionPerformed

    private void jBtnActDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActDesActionPerformed
        cambiarEstado();
    }//GEN-LAST:event_jBtnActDesActionPerformed

    private void cambiarEstado() {
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        int fila = jTblArticulos.getSelectedRow();
        if (fila != -1) {
            try {
                int n = JOptionPane.showConfirmDialog(null, "¿Seguro que desea cambiar el estado del articulo?","Cambio de estado", JOptionPane.YES_NO_OPTION);
                if (n == JOptionPane.OK_OPTION) {
                    String sql = "";
                    if (jTblArticulos.getValueAt(fila, 6).equals("N")) {
                        sql = "UPDATE PRODUCTOS SET EST_PRO = 'Y' WHERE ID_PRO = '" + jTblArticulos.getValueAt(fila, 0) + "'";
                    } else {
                        sql = "UPDATE PRODUCTOS SET EST_PRO = 'N' WHERE ID_PRO = '" + jTblArticulos.getValueAt(fila, 0) + "'";
                    }
                    PreparedStatement psd = cn.prepareStatement(sql);
                    psd.executeUpdate();
                    cargarTabla();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActDes;
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTblArticulos;
    // End of variables declaration//GEN-END:variables
}
